name: Build and Deploy Dockerized Node.js App to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: call-notificationv1
  AZURE_RESOURCE_GROUP: call-notifi_rg
  REGISTRY_LOGIN_SERVER: acrcall.azurecr.io
  IMAGE_NAME: callnotification

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $REGISTRY_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: call-notificationv1
          images: callnotification:latest

      - name: Deploy to Azure Web App (via Deployment Center)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.IMAGE_NAME }}:latest
