name: Build and Deploy to Azure Web App (Docker)

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  IMAGE_NAME: callnotification

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          docker build -t $REGISTRY_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $REGISTRY_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
